baseURL = 'https://maverick.canhtran.me'
languageCode = 'de-ch'
title = 'Subcultura lebt'
paginate = 3
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "Gisi bleibt!"
  author = 'Subcultura'

  [params.comments]
    enabled = false
    githubRepo = 'canhtran/maverick'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "Über die Gisi"
    url = "/gisi"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Unsere Freund*innen"
    url = "/freundinnen"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]